### ISSUE TITLE
Unable to create HorovodRayPlugin due to missing horovod API

### ISSUE THREAD

**Issue by hanli-0612** [ray-project/ray_lightning#139]
Hi,

I'm trying to re-run [this](https://github.com/ray-project/ray_lightning/blob/main/ray_lightning/examples/ray_horovod_example.py) example code locally on my laptop, and observed the following issue:

```
Traceback (most recent call last):
  File "workflow/ray_horovod_example.py", line 127, in <module>
    train_mnist(config, data_dir, num_epochs, num_workers, use_gpu)
  File "workflow/ray_lightning_horovod.py", line 74, in train_mnist
    plugins=[HorovodRayPlugin(num_workers=num_workers, use_gpu=use_gpu)])
  File "/usr/local/lib/python3.7/site-packages/ray_lightning/ray_horovod.py", line 84, in __init__
    super().__init__()
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/horovod.py", line 46, in __init__
    rank_zero_only.rank = self.global_rank
  File "/usr/local/lib/python3.7/site-packages/ray_lightning/ray_horovod.py", line 102, in global_rank
    if not hvd.is_initialized():
AttributeError: module 'horovod.torch' has no attribute 'is_initialized'
```

The packages I've installed in my test:
```
horovod==0.24.2
pytorch-lightning==1.5.9
ray==1.11.0
ray-lightning==0.2.0
threadpoolctl==3.1.0
torch==1.11.0
torchvision==0.12.0
```

Could I get some help in debugging this missing API? Thanks for the help in advance!

**Comment by amogkam** [comment]
Hey @hanli-0612 how are you installing horovod? Is it being installed with PyTorch support enabled? `HOROVOD_WITH_PYTORCH=1 pip install horovod[pytorch]`. https://horovod.readthedocs.io/en/stable/install_include.html#pytorch

**Comment by hanli-0612** [comment]
@amogkam Thank you it works! Closing the issue :)
