### ISSUE TITLE
ray-lightning doesn't seem to be compatible with ray 2.3

### ISSUE THREAD

**Issue by marcosrdac** [ray-project/ray_lightning#255]
Warning got at the begining of my training code seems like ray lightning is using deprecated API for getting node id:

```
.../lib/python3.8/site-packages/ray_lightning/launchers/utils.py:48: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS="ignore::DeprecationWarning"
Use get_node_id() instead
  return ray.get_runtime_context().node_id.hex(), ray.get_gpu_ids()
```

Error in 13th epoch seems to be related to that (idk why future deprecation would get me an error, but this is the only problem I've found until now):

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File /petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/execution/trial_runner.py:924, in TrialRunner._wait_and_handle_event(self, next_trial)
    923 if event.type == _ExecutorEventType.TRAINING_RESULT:
--> 924     self._on_training_result(
    925         trial, result[_ExecutorEvent.KEY_FUTURE_RESULT]
    926     )
    927 else:

File /petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/execution/trial_runner.py:1047, in TrialRunner._on_training_result(self, trial, result)
   1046 with warn_if_slow("process_trial_result"):
-> 1047     self._process_trial_results(trial, result)

File /petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/execution/trial_runner.py:1130, in TrialRunner._process_trial_results(self, trial, results)
   1129 with warn_if_slow("process_trial_result"):
-> 1130     decision = self._process_trial_result(trial, result)
   1131 if decision is None:
   1132     # If we didn't get a decision, this means a
   1133     # non-training future (e.g. a save) was scheduled.
   1134     # We do not allow processing more results then.

File /petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/execution/trial_runner.py:1185, in TrialRunner._process_trial_result(self, trial, result)
   1184 with warn_if_slow("callbacks.on_trial_result"):
-> 1185     self._callbacks.on_trial_result(
   1186         iteration=self._iteration,
   1187         trials=self._trials,
   1188         trial=trial,
   1189         result=result.copy(),
   1190     )
   1191 trial.update_last_result(result)

File /petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/callback.py:356, in CallbackList.on_trial_result(self, **info)
    355 for callback in self._callbacks:
--> 356     callback.on_trial_result(**info)

File /petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/syncer.py:726, in SyncerCallback.on_trial_result(self, iteration, trials, trial, result, **info)
    718 def on_trial_result(
    719     self,
    720     iteration: int,
   (...)
    724     **info,
    725 ):
--> 726     self._sync_trial_dir(trial, force=False, wait=False)

File /petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/syncer.py:685, in SyncerCallback._sync_trial_dir(self, trial, force, wait)
    684 try:
--> 685     sync_process.wait()
    686 except TuneError as e:
    687     # Errors occurring during this wait are not fatal for this
    688     # checkpoint, so it should just be logged.

File /petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/syncer.py:237, in _BackgroundProcess.wait(self, timeout)
    236 if exception:
--> 237     raise exception
    239 result = self._result.get("result")

File /petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/syncer.py:200, in _BackgroundProcess.start.<locals>.entrypoint()
    199 try:
--> 200     result = self._fn(*args, **kwargs)
    201 except Exception as e:

File /petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/utils/file_transfer.py:69, in sync_dir_between_nodes(source_ip, source_path, target_ip, target_path, force_all, exclude, chunk_size_bytes, max_size_bytes, return_futures)
     68 if source_ip != target_ip:
---> 69     return _sync_dir_between_different_nodes(
     70         source_ip=source_ip,
     71         source_path=source_path,
     72         target_ip=target_ip,
     73         target_path=target_path,
     74         force_all=force_all,
     75         exclude=exclude,
     76         chunk_size_bytes=chunk_size_bytes,
     77         max_size_bytes=max_size_bytes,
     78         return_futures=return_futures,
     79     )
     80 elif source_path != target_path:

File /petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/utils/file_transfer.py:175, in _sync_dir_between_different_nodes(source_ip, source_path, target_ip, target_path, force_all, exclude, chunk_size_bytes, max_size_bytes, return_futures)
    171 pack_actor_on_source_node = _PackActor.options(
    172     num_cpus=0, **_force_on_node(source_node_id)
    173 )
    174 unpack_on_target_node = _unpack_from_actor.options(
--> 175     num_cpus=0, **_force_on_node(target_node_id)
    176 )
    178 if force_all:

File /petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/air/util/node.py:35, in _force_on_node(node_id, remote_func_or_actor_class)
     20 """Schedule a remote function or actor class on a given node.
     21 
     22 Args:
   (...)
     32     actor class as remote options kwargs.
     33 """
---> 35 scheduling_strategy = ray.util.scheduling_strategies.NodeAffinitySchedulingStrategy(
     36     node_id=node_id, soft=False
     37 )
     39 options = {"scheduling_strategy": scheduling_strategy}

File /petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/util/scheduling_strategies.py:61, in NodeAffinitySchedulingStrategy.__init__(self, node_id, soft)
     60 if not isinstance(node_id, str):
---> 61     node_id = node_id.hex()
     63 self.node_id = node_id

AttributeError: 'NoneType' object has no attribute 'hex'

During handling of the above exception, another exception occurred:

TuneError                                 Traceback (most recent call last)
File /petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/tuner.py:292, in Tuner.fit(self)
    291 try:
--> 292     return self._local_tuner.fit()
    293 except TuneError as e:

File /petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/impl/tuner_internal.py:455, in TunerInternal.fit(self)
    454     param_space = copy.deepcopy(self._param_space)
--> 455     analysis = self._fit_internal(trainable, param_space)
    456 else:

File /petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/impl/tuner_internal.py:572, in TunerInternal._fit_internal(self, trainable, param_space)
    559 args = {
    560     **self._get_tune_run_arguments(trainable),
    561     **dict(
   (...)
    570     **self._tuner_kwargs,
    571 }
--> 572 analysis = run(
    573     **args,
    574 )
    575 self.clear_remote_string_queue()

File /petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/tune.py:756, in run(run_or_experiment, name, metric, mode, stop, time_budget_s, config, resources_per_trial, num_samples, local_dir, search_alg, scheduler, keep_checkpoints_num, checkpoint_score_attr, checkpoint_freq, checkpoint_at_end, verbose, progress_reporter, log_to_file, trial_name_creator, trial_dirname_creator, chdir_to_trial_dir, sync_config, export_formats, max_failures, fail_fast, restore, server_port, resume, reuse_actors, raise_on_failed_trial, callbacks, max_concurrent_trials, trial_executor, _experiment_checkpoint_dir, _remote, _remote_string_queue)
    755 while not runner.is_finished() and not experiment_interrupted_event.is_set():
--> 756     runner.step()
    757     if has_verbosity(Verbosity.V1_EXPERIMENT):

File /petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/execution/trial_runner.py:957, in TrialRunner.step(self)
    955     logger.debug(f"Got new trial to run: {next_trial}")
--> 957 self._wait_and_handle_event(next_trial)
    959 self._stop_experiment_if_needed()

File /petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/execution/trial_runner.py:936, in TrialRunner._wait_and_handle_event(self, next_trial)
    935 else:
--> 936     raise TuneError(traceback.format_exc())

TuneError: Traceback (most recent call last):
  File "/petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/execution/trial_runner.py", line 924, in _wait_and_handle_event
    self._on_training_result(
  File "/petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/execution/trial_runner.py", line 1047, in _on_training_result
    self._process_trial_results(trial, result)
  File "/petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/execution/trial_runner.py", line 1130, in _process_trial_results
    decision = self._process_trial_result(trial, result)
  File "/petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/execution/trial_runner.py", line 1185, in _process_trial_result
    self._callbacks.on_trial_result(
  File "/petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/callback.py", line 356, in on_trial_result
    callback.on_trial_result(**info)
  File "/petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/syncer.py", line 726, in on_trial_result
    self._sync_trial_dir(trial, force=False, wait=False)
  File "/petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/syncer.py", line 685, in _sync_trial_dir
    sync_process.wait()
  File "/petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/syncer.py", line 237, in wait
    raise exception
  File "/petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/syncer.py", line 200, in entrypoint
    result = self._fn(*args, **kwargs)
  File "/petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/utils/file_transfer.py", line 69, in sync_dir_between_nodes
    return _sync_dir_between_different_nodes(
  File "/petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/utils/file_transfer.py", line 175, in _sync_dir_between_different_nodes
    num_cpus=0, **_force_on_node(target_node_id)
  File "/petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/air/util/node.py", line 35, in _force_on_node
    scheduling_strategy = ray.util.scheduling_strategies.NodeAffinitySchedulingStrategy(
  File "/petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/util/scheduling_strategies.py", line 61, in __init__
    node_id = node_id.hex()
AttributeError: 'NoneType' object has no attribute 'hex'


The above exception was the direct cause of the following exception:

TuneError                                 Traceback (most recent call last)
Cell In[40], line 108
     83     return
     86 tuner = tune.Tuner(
     87     tune.with_resources(
     88         partial(
   (...)
    105     param_space=param_space,
    106 )
--> 108 results = tuner.fit()

File /petrobr/parceirosbr/smartseg/marcos.conceicao/.home/.conda/envs/msseg/lib/python3.8/site-packages/ray/tune/tuner.py:294, in Tuner.fit(self)
    292         return self._local_tuner.fit()
    293     except TuneError as e:
--> 294         raise TuneError(
    295             _TUNER_FAILED_MSG.format(
    296                 path=self._local_tuner.get_experiment_checkpoint_dir()
    297             )
    298         ) from e
    299 else:
    300     experiment_checkpoint_dir = ray.get(
    301         self._remote_tuner.get_experiment_checkpoint_dir.remote()
    302     )

TuneError: The Ray Tune run failed. Please inspect the previous error messages for a cause. After fixing the issue, you can restart the run from scratch or continue this run. To continue this run, you can use `tuner = Tuner.restore("/petrobr/parceirosbr/home/marcos.conceicao/ray_results/train_2023-03-30_16-35-42")`.
```

I've downgraded ray to 2.1 to see how the same code does.

**Comment by woshiyyya** [comment]
Hi @marcosrdac, sorry for the inconvenience. ray-lightning hasn't been keeping up with Ray recently and we plan to deprecate it in the near future. The good news is that we will introduce the `LightningTrainer` in Ray 2.4, which provides native integration with Ray AIR!!

Although we haven't release 2.4 yet, you can install our [nightly wheel](https://docs.ray.io/en/master/ray-overview/installation.html#daily-releases-nightlies) to try out our [LightningTrainer](https://docs.ray.io/en/master/train/api/api.html#pytorch-lightning). Here are some reference docs for you to get familiar with it:
- [Using LightningTrainer for DDP training](https://docs.ray.io/en/master/train/examples/lightning/lightning_mnist_example.html#lightning-mnist-example). 
- [Use LightningTrainer for Ray Tune.](https://github.com/ray-project/ray/blob/master/release/lightning_tests/workloads/test_tuner.py) 
 
We are updating our document to have more docs and examples. Let me know if you have any questions onboarding LightningTrainer.

**Comment by marcosrdac** [comment]
Thank you for the update. Anyway, downgrading ray to version 2.1.0 solved the problem for me.
