### ISSUE TITLE
Can't use ray_lightning in pytest

### ISSUE THREAD

**Issue by Rizhiy** [ray-project/ray_lightning#60]
Hi,

When I try to run the code with RayPlugin in my tests, I get the following error:
```
(pid=2127144) 2021-07-14 06:16:52,345   ERROR serialization.py:250 -- No module named 'test_runner'
(pid=2127144) Traceback (most recent call last):
(pid=2127144)   File "/home/rizhiy/miniconda3/envs/ntf/lib/python3.8/site-packages/ray/serialization.py", line 248, in deserialize_objects
(pid=2127144)     obj = self._deserialize_object(data, metadata, object_ref)
(pid=2127144)   File "/home/rizhiy/miniconda3/envs/ntf/lib/python3.8/site-packages/ray/serialization.py", line 190, in _deserialize_object
(pid=2127144)     return self._deserialize_msgpack_data(data, metadata_fields)
(pid=2127144)   File "/home/rizhiy/miniconda3/envs/ntf/lib/python3.8/site-packages/ray/serialization.py", line 168, in _deserialize_msgpack_data
(pid=2127144)     python_objects = self._deserialize_pickle5_data(pickle5_data)
(pid=2127144)   File "/home/rizhiy/miniconda3/envs/ntf/lib/python3.8/site-packages/ray/serialization.py", line 158, in _deserialize_pickle5_data
(pid=2127144)     obj = pickle.loads(in_band)
(pid=2127144) ModuleNotFoundError: No module named 'test_runner'
```

`test_runner` is the name of my testing script, but I'm not sure why you would need to serialize anything inside it. It just loads data and calls `Runner`, which is my wrapper around `pl.Trainer`.

How should I properly launch the training?

**Comment by amogkam** [comment]
Hey @Rizhiy, could you share the `test_runner` script, the full log output, and more information about your setup (how many nodes in the cluster and ray version)

**Comment by Rizhiy** [comment]
Sure, here is the relevant section of `test_runner`:
```python
def _test_train(data, runner):
    train_dataset = DictTensorDataset(data["train"])
    val_dataset = DictTensorDataset(data["val"])

    rmtree(runner.output_dir, ignore_errors=True)
    runner.output_dir.mkdir()

    runner.train_model(train_dataset, val_dataset)


@pytest.mark.limit_gpus(2)
@pytest.mark.dependency()
def test_train(load_file, runner):
    _test_train(load_file("data.pkl"), runner)
 ```

Here is relevant parts of the `Runner`:
```python
    def _create_trainer(self, *_, **kwargs) -> pl.Trainer:
        base_kwargs = dict(
            default_root_dir=str(self.output_dir.absolute()),
            gpus=1,
            precision=16 if self.cfg.FP16 else 32,
        )
        base_kwargs.update(kwargs)
        plugins = [
            RayPlugin(num_workers=self.cfg.NUM_GPUS, num_cpus_per_worker=1, use_gpu=True, find_unused_parameters=False),
        ]
        if "plugins" not in base_kwargs:
            base_kwargs["plugins"] = []
        base_kwargs["plugins"].extend(plugins)
        return pl.Trainer(**base_kwargs)

    def train_model(self, train_dataset: DictsDataset, val_dataset: DictsDataset):
        pip_freeze(self.requirements_path)
        seed_everything(self.cfg.SEED)
        checkpoint_callback = ModelCheckpoint(
            monitor=f"{self.cfg.VAL.SELECTION_TARGET}.{self.cfg.VAL.SELECTION_METRIC}",
            mode="min" if self.cfg.VAL.MINIMISE_METRIC else "max",
            filename="{step:05d}",
            save_top_k=1,
            save_last=True,
        )
        last_checkpoint_path = self.output_dir / "lightning_logs" / "version_0" / "checkpoints" / "last.ckpt"
        trainer = self._create_trainer(
            sync_batchnorm=True,
            max_steps=self.cfg.TRAIN.NUM_ITERS,
            resume_from_checkpoint=str(last_checkpoint_path) if last_checkpoint_path.exists() else None,
            callbacks=[checkpoint_callback],
            val_check_interval=self.cfg.VAL.FREQ,
        )

        trainer.fit(self, datamodule=self._create_datamodule({"train": train_dataset, "val": val_dataset}))
```

**Comment by Rizhiy** [comment]
Here is extra stack trace:
```
tests/training/test_runner.py:114: in _test_train
    runner.train_model(train_dataset, val_dataset)
ntf/training/runner.py:243: in train_model
    trainer.fit(self, datamodule=self._create_datamodule({"train": train_dataset, "val": val_dataset}))
../../miniconda3/envs/ntf/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:458: in fit
    self._run(model)
../../miniconda3/envs/ntf/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:756: in _run
    self.dispatch()
../../miniconda3/envs/ntf/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:797: in dispatch
    self.accelerator.start_training(self)
../../miniconda3/envs/ntf/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py:96: in start_training
    self.training_type_plugin.start_training(trainer)
../../miniconda3/envs/ntf/lib/python3.8/site-packages/ray_lightning/ray_ddp.py:213: in start_training
    results = self.execution_loop(trainer, tune_enabled=True)
../../miniconda3/envs/ntf/lib/python3.8/site-packages/ray_lightning/ray_ddp.py:195: in execution_loop
    results = process_results(futures, queue)
../../miniconda3/envs/ntf/lib/python3.8/site-packages/ray_lightning/util.py:103: in process_results
    ray.get(ready)
../../miniconda3/envs/ntf/lib/python3.8/site-packages/ray/_private/client_mode_hook.py:62: in wrapper
    return func(*args, **kwargs)
 ```

**Comment by amogkam** [comment]
actually do you mind sharing the entirety of `test_runner`? In particular I want to see where `DictTensorDataset` is defined.

**Comment by amogkam** [comment]
I think you might be running into this same error https://github.com/ray-project/ray/issues/13528

**Comment by Rizhiy** [comment]
It is defined above that function, should it also be pickleable?

**Comment by amogkam** [comment]
Ok got it, see the issue that I linked. I think this should work if you move `DictTensorDataset` to a separate file.

**Comment by Rizhiy** [comment]
Thanks, that fixed it.
