### ISSUE TITLE
CUDA devices are not exposed when running in DDP mode with multiple GPUs

### ISSUE THREAD

**Issue by MarkusSpanring** [ray-project/ray_lightning#84]
Hi all!

First of all thanks for this great project!

To my issue:
When I tried your [example](https://github.com/ray-project/ray_lightning/tree/bc59fd4cb067d7e1ac1197d9a4e6fac1427cbd45#hyperparameter-tuning-with-ray-tune) for hyperparameter tuning I discovered that it only worked when using `cpu`. After some digging, I found out that the problem is related to [get_tune_ddp_resources](https://github.com/ray-project/ray_lightning/blob/bc59fd4cb067d7e1ac1197d9a4e6fac1427cbd45/ray_lightning/tune.py#L29)
Since `head_bundle` only requests `cpu` it does not expose the required CUDA devices for the child bundles. Therefore, Lightning fails to run on GPU(s) since `CUDA_VISIBLE_DEVICES` is not set.

As a workaround, I have added 
```
if use_gpu:
        os.environ["CUDA_VISIBLE_DEVICES"] = ",".join([str(i) for i in range(num_workers)])
```
in `__init__` of [RayPlugin](https://github.com/ray-project/ray_lightning/blob/bc59fd4cb067d7e1ac1197d9a4e6fac1427cbd45/ray_lightning/ray_ddp.py#L57)
It gets the job done but seems incredibly hacky. Is there some other way around?

Thanks in advance!

**Comment by amogkam** [comment]
Hey @MarkusSpanring, just making sure are you also passing in `use_gpu=True` into `get_tune_ddp_resources`?

**Comment by MarkusSpanring** [comment]
Hey @amogkam! Thanks for the quick reply.  Thanks for also replying here [here](https://discuss.ray.io/t/tune-detects-gpus-warning-trigger-even-though-gpu-is-requested-in-resources-per-trial/3433/2). I should have added this also here and not only in the Forum. Yes, I have set
```
...
       resources_per_trial=get_tune_ddp_resources(
            num_workers=1,
            cpus_per_worker=1,
            use_gpu=True
        ),
```

This should give me `tune.PlacementGroupFactory([{"CPU": 1}, {"CPU": 1, "GPU": 1}, strategy=PACK])` right?
It seems that due to the `head_bundle` being just `{"CPU":1}` ray does not expose the needed `CUDA_VISIBLE_DEVICES` to the workers. 

This can be replicated with 

```
def dummy_function(config):
    print("VISIBLE: ", os.environ.get("CUDA_VISIBLE_DEVICES", None))
    tune.report(minimum=config["value"])

def tune_dummy_placement_group():

    config = {"value": tune.loguniform(1e-4, 1e-1)}

    analysis = tune.run(
        tune.with_parameters(dummy_function),
        resources_per_trial=tune.PlacementGroupFactory([{"CPU": 1}, {"CPU": 1, "GPU": 1}]),
        metric="minimum",
        config=config,
        verbose=0,
        mode="min",
        num_samples=3
    )

def tune_dummy_placement_group_gpu_both():

    config = {"value": tune.loguniform(1e-4, 1e-1)}

    analysis = tune.run(
        tune.with_parameters(dummy_function),
        resources_per_trial=tune.PlacementGroupFactory([{"CPU": 1, "GPU": 1}, {"CPU": 1, "GPU": 1}]),
        metric="minimum",
        config=config,
        verbose=0,
        mode="min",
        num_samples=3
    )
```
With `tune_dummy_placement_group_gpu_both()` I see `CUDA_VISIBLE_DEVICES`.

**Comment by amogkam** [comment]
Ah yes the head bundle not having GPUs is expected behavior. The reason for this is that Ray Lightning spawns new actors to actually execute the training. These actors are placed on the child bundles which require GPU. However, no training actually occurs on the main process, so if the head bundle contains GPUs, then it would just be idle and thus would be a waste. Therefore, we don't expose GPUs on the head bundle. Even with this setup, the example should work with GPU.

Just to clarify, is training not working for you? Or is it still working, but it's just that `CUDA_VISIBLE_DEVICES` is not being set on the main process (which is expected behavior)? Is there a reason you need this to be set?

**Comment by MarkusSpanring** [comment]
Training is only working with CPU but not with GPU.  

I fully understand that the head bundle not having GPUs is desired/expected in that case. However, it seems that when Lightning is trying to allocate the GPUs it is using the `CUDA_VISIBLE_DEVICES` provided in the main process. Since there is no GPU exposed there, training fails. So I only managed to run training on GPU by setting  `CUDA_VISIBLE_DEVICES` with the workaround I described above.

**Comment by amogkam** [comment]
@MarkusSpanring what version of PyTorch Lightning do you have? Are you running the example script exactly as is? Can you share the full output you are seeing?

**Comment by MarkusSpanring** [comment]
@amogkam I use
```
python3.8.10
pytorch=1.9.0=py3.8_cuda11.1_cudnn8.0.5_0
pytorch-lightning==1.4.2
ray==1.6.0
ray_lightning==0.1.1
```
I created a gist with the setup I am using to run the tests [here](https://gist.github.com/MarkusSpanring/b0d4095241093f394031302e6c48a782)
From this I get the following output
```bash
/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/ray/_private/services.py:238: UserWarning: Not all Ray Dashboard dependencies were found. To use the dashboard please install Ray using `pip install ray[default]`. To disable this message, set RAY_DISABLE_IMPORT_WARNING env var to '1'.
  warnings.warn(warning_message)
2021-09-03 14:17:55,360	WARNING function_runner.py:558 -- Function checkpointing is disabled. This may result in unexpected behavior when using checkpointing features or certain schedulers. To enable, set the train function arguments to be `func(config, checkpoint_dir=None)`.
2021-09-03 14:17:55,427	WARNING tune.py:506 -- Tune detects GPUs, but no trials are using GPUs. To enable trials to use GPUs, set tune.run(resources_per_trial={'gpu': 1}...) which allows Tune to expose 1 GPU to each trial. You can also override `Trainable.default_resource_request` if using the Trainable API.
== Status ==
Memory usage on this node: 20.9/1510.6 GiB
Using AsyncHyperBand: num_stopped=0
Bracket: Iter 8.000: None | Iter 4.000: None | Iter 2.000: None | Iter 1.000: None
Resources requested: 0/72 CPUs, 0/14 GPUs, 0.0/1310.36 GiB heap, 0.0/186.26 GiB objects (0.0/1.0 accelerator_type:T4)
Result logdir: /home/markus.spanring/ray_results/tune_mnist_asha
Number of trials: 1/1 (1 PENDING)
+------------------------------+----------+-------+----------------+----------------+-------------+--------------+
| Trial name                   | status   | loc   |   layer_1_size |   layer_2_size |          lr |   batch_size |
|------------------------------+----------+-------+----------------+----------------+-------------+--------------|
| train_mnist_tune_f7de4_00000 | PENDING  |       |             32 |            256 | 0.000899789 |           64 |
+------------------------------+----------+-------+----------------+----------------+-------------+--------------+


(pid=15017) /home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/torchvision/datasets/mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448278899/work/torch/csrc/utils/tensor_numpy.cpp:180.)
(pid=15017)   return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)
2021-09-03 14:17:57,228	ERROR trial_runner.py:773 -- Trial train_mnist_tune_f7de4_00000: Error processing event.
Traceback (most recent call last):
  File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 739, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 746, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/ray/worker.py", line 1621, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TuneError): ray::ImplicitFunc.train_buffered() (pid=15017, ip=10.50.0.19, repr=<ray.tune.function_runner.ImplicitFunc object at 0x7fc09f39f9d0>)
  File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/ray/tune/trainable.py", line 178, in train_buffered
    result = self.train()
  File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/ray/tune/trainable.py", line 237, in train
    result = self.step()
  File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/ray/tune/function_runner.py", line 379, in step
    self._report_thread_runner_error(block=True)
  File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/ray/tune/function_runner.py", line 526, in _report_thread_runner_error
    raise TuneError(
ray.tune.error.TuneError: Trial raised an exception. Traceback:
ray::ImplicitFunc.train_buffered() (pid=15017, ip=10.50.0.19, repr=<ray.tune.function_runner.ImplicitFunc object at 0x7fc09f39f9d0>)
  File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/ray/tune/function_runner.py", line 260, in run
    self._entrypoint()
  File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/ray/tune/function_runner.py", line 328, in entrypoint
    return self._trainable_func(self.config, self._status_reporter,
  File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/ray/tune/function_runner.py", line 594, in _trainable_func
    output = fn()
  File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/ray/tune/utils/trainable.py", line 353, in _inner
    inner(config, checkpoint_dir=None)
  File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/ray/tune/utils/trainable.py", line 344, in inner
    trainable(config, **fn_kwargs)
  File "tune_model.py", line 121, in train_mnist_tune
    trainer = pl.Trainer(
  File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 40, in insert_env_defaults
    return fn(self, **kwargs)
  File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 346, in __init__
    gpu_ids, tpu_cores = self._parse_devices(gpus, auto_select_gpus, tpu_cores)
  File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1251, in _parse_devices
    gpu_ids = device_parser.parse_gpu_ids(gpus)
  File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/pytorch_lightning/utilities/device_parser.py", line 91, in parse_gpu_ids
    return _sanitize_gpu_ids(gpus)
  File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/pytorch_lightning/utilities/device_parser.py", line 163, in _sanitize_gpu_ids
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: You requested GPUs: [0]
 But your machine only has: []
== Status ==
Memory usage on this node: 21.2/1510.6 GiB
Using AsyncHyperBand: num_stopped=0
Bracket: Iter 8.000: None | Iter 4.000: None | Iter 2.000: None | Iter 1.000: None
Resources requested: 0/72 CPUs, 0/14 GPUs, 0.0/1310.36 GiB heap, 0.0/186.26 GiB objects (0.0/1.0 accelerator_type:T4)
Result logdir: /home/markus.spanring/ray_results/tune_mnist_asha
Number of trials: 1/1 (1 ERROR)
+------------------------------+----------+-------+----------------+----------------+-------------+--------------+
| Trial name                   | status   | loc   |   layer_1_size |   layer_2_size |          lr |   batch_size |
|------------------------------+----------+-------+----------------+----------------+-------------+--------------|
| train_mnist_tune_f7de4_00000 | ERROR    |       |             32 |            256 | 0.000899789 |           64 |
+------------------------------+----------+-------+----------------+----------------+-------------+--------------+
Number of errored trials: 1
+------------------------------+--------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Trial name                   |   # failures | error file                                                                                                                                                                        |
|------------------------------+--------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| train_mnist_tune_f7de4_00000 |            1 | /home/markus.spanring/ray_results/tune_mnist_asha/train_mnist_tune_f7de4_00000_0_batch_size=64,layer_1_size=32,layer_2_size=256,lr=0.00089979_2021-09-03_14-17-55/error.txt |
+------------------------------+--------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

(pid=15017) 2021-09-03 14:17:57,212	ERROR function_runner.py:266 -- Runner Thread raised error.
(pid=15017) Traceback (most recent call last):
(pid=15017)   File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/ray/tune/function_runner.py", line 260, in run
(pid=15017)     self._entrypoint()
(pid=15017)   File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/ray/tune/function_runner.py", line 328, in entrypoint
(pid=15017)     return self._trainable_func(self.config, self._status_reporter,
(pid=15017)   File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/ray/tune/function_runner.py", line 594, in _trainable_func
(pid=15017)     output = fn()
(pid=15017)   File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/ray/tune/utils/trainable.py", line 353, in _inner
(pid=15017)     inner(config, checkpoint_dir=None)
(pid=15017)   File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/ray/tune/utils/trainable.py", line 344, in inner
(pid=15017)     trainable(config, **fn_kwargs)
(pid=15017)   File "tune_model.py", line 121, in train_mnist_tune
(pid=15017)     trainer = pl.Trainer(
(pid=15017)   File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 40, in insert_env_defaults
(pid=15017)     return fn(self, **kwargs)
(pid=15017)   File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 346, in __init__
(pid=15017)     gpu_ids, tpu_cores = self._parse_devices(gpus, auto_select_gpus, tpu_cores)
(pid=15017)   File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1251, in _parse_devices
(pid=15017)     gpu_ids = device_parser.parse_gpu_ids(gpus)
(pid=15017)   File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/pytorch_lightning/utilities/device_parser.py", line 91, in parse_gpu_ids
(pid=15017)     return _sanitize_gpu_ids(gpus)
(pid=15017)   File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/pytorch_lightning/utilities/device_parser.py", line 163, in _sanitize_gpu_ids
(pid=15017)     raise MisconfigurationException(
(pid=15017) pytorch_lightning.utilities.exceptions.MisconfigurationException: You requested GPUs: [0]
(pid=15017)  But your machine only has: []
(pid=15017) Exception in thread Thread-2:
(pid=15017) Traceback (most recent call last):
(pid=15017)   File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/threading.py", line 932, in _bootstrap_inner
(pid=15017)     self.run()
(pid=15017)   File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/ray/tune/function_runner.py", line 279, in run
(pid=15017)     raise e
(pid=15017)   File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/ray/tune/function_runner.py", line 260, in run
(pid=15017)     self._entrypoint()
(pid=15017)   File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/ray/tune/function_runner.py", line 328, in entrypoint
(pid=15017)     return self._trainable_func(self.config, self._status_reporter,
(pid=15017)   File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/ray/tune/function_runner.py", line 594, in _trainable_func
(pid=15017)     output = fn()
(pid=15017)   File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/ray/tune/utils/trainable.py", line 353, in _inner
(pid=15017)     inner(config, checkpoint_dir=None)
(pid=15017)   File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/ray/tune/utils/trainable.py", line 344, in inner
(pid=15017)     trainable(config, **fn_kwargs)
(pid=15017)   File "tune_model.py", line 121, in train_mnist_tune
(pid=15017)     trainer = pl.Trainer(
(pid=15017)   File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 40, in insert_env_defaults
(pid=15017)     return fn(self, **kwargs)
(pid=15017)   File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 346, in __init__
(pid=15017)     gpu_ids, tpu_cores = self._parse_devices(gpus, auto_select_gpus, tpu_cores)
(pid=15017)   File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1251, in _parse_devices
(pid=15017)     gpu_ids = device_parser.parse_gpu_ids(gpus)
(pid=15017)   File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/pytorch_lightning/utilities/device_parser.py", line 91, in parse_gpu_ids
(pid=15017)     return _sanitize_gpu_ids(gpus)
(pid=15017)   File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/pytorch_lightning/utilities/device_parser.py", line 163, in _sanitize_gpu_ids
(pid=15017)     raise MisconfigurationException(
(pid=15017) pytorch_lightning.utilities.exceptions.MisconfigurationException: You requested GPUs: [0]
(pid=15017)  But your machine only has: []
Traceback (most recent call last):
  File "tune_model.py", line 182, in <module>
    tune_mnist_asha(1, 10, 1, 1)
  File "tune_model.py", line 163, in tune_mnist_asha
    analysis = tune.run(
  File "/home/markus.spanring/.conda/envs/torch/lib/python3.8/site-packages/ray/tune/tune.py", line 555, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [train_mnist_tune_f7de4_00000])
```

**Comment by amogkam** [comment]
@MarkusSpanring thanks! Can you not specify gpus in the Trainer? Then this should work.

**Comment by MarkusSpanring** [comment]
@amogkam yes, that works. Thanks!
 I also have a problem when specifying `num_workers` in the  `DataLoader`. I can open a new Issue if you say so but let me ask it here already.
 How should I specify `num_workers` for the dataloader. Currently  I specify `num_workers` in `DataLoader(self.mnist_train, batch_size=int(self.batch_size), num_workers=4)` e.g. [here](https://gist.github.com/MarkusSpanring/b0d4095241093f394031302e6c48a782#file-tune_ptl-py-L104) and increase `num_cpus_per_worker` in the `RayPlugin` also to 4 (I also tried a larger number then `num
 _workers` specified in the `DataLoader`). I do not get any error but some of the workers do not clean up `GPU` memory when they finishing and stay alive after the tuning run. Until now I was not able to fully reproduce the behavior unfortunately but in 3 out of 4 runs I get such processes.

**Comment by amogkam** [comment]
Hey @MarkusSpanring, they way you are doing this sounds right. Could you post a new issue about the GPU memory not being cleaned up?

**Comment by MarkusSpanring** [comment]
@amogkam will do.
Thanks for the help with this!

From my side, the issue can be closed.
