### ISSUE TITLE
ValueError: Message ray.rpc.DataRequest exceeds maximum protobuf size of 2GB

### ISSUE THREAD

**Issue by juyunsang** [ray-project/ray_lightning#86]
Hello
Training with large size data(2GB) results in the following error.
There is no problem with small size of learning data

```
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
2021-09-06 17:15:49,920 [ERROR] Exception serializing message!
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/grpc/_common.py", line 86, in _transform
    return transformer(message)
ValueError: Message ray.rpc.DataRequest exceeds maximum protobuf size of 2GB: 2339503268
2021-09-06 17:15:49,925 [ERROR] Got Error from data channel -- shutting down:
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/ray/util/client/dataclient.py", line 69, in _data_main
    for response in resp_stream:
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/grpc/_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.INTERNAL
        details = "Exception serializing request!"
        debug_error_string = "None"
>
```

**Comment by amogkam** [comment]
Hey @juyunsang, I am going to move this over as an issue to the main Ray repo. Can you provide a reproducible script for this error? Thanks.
